<a href="https://colab.research.google.com/github/madanjha/PythonDS/blob/main/16_11_2024_Linear_Algebra_Handson_by_Tanmay.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Matrix Operations
**Q1: Basic Matrix Operations**

Create two matrices:

A random matrix of shape  (3x2)

 B random matrix of shape  (2x3)

Perform the following operations:

**Matrix Addition: Compute A + B (if possible).**

**Matrix Multiplication: Compute the product of matrices A * B (if possible).**

**Scalar Multiplication: Multiply matrix A by a scalar k = 5.**


In [ ]:
import numpy as np

In [ ]:
A= np.random.randint(1,5,size=(3,2))
B= np.random.randint(1,5,size=(2,3))

In [ ]:
A

array([[1, 4],
       [3, 4],
       [3, 3]])

In [ ]:
B

array([[2, 4, 2],
       [1, 2, 3]])

In [ ]:
A+B # addition is not possible for the dissimilar shapes of matrix

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [ ]:
A*B # multiplication is not possible for the dissimilar shapes of matrix

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [ ]:
A

array([[1, 4],
       [3, 4],
       [3, 3]])

In [ ]:
5*A

array([[ 5, 20],
       [15, 20],
       [15, 15]])

# Dot and Cross Product
**Q2: Dot and Cross Product**

Create two 3D vectors:

v1 = [1, 2, 3]
v2 = [4, 5, 6]
Compute the following:

Dot Product: Calculate the dot product of v1 and v2.

Cross Product: Calculate the cross product of v1 and v2.

In [ ]:
v1= np.array([1,2,3])
v2= np.array([4,5,6])

In [ ]:
np.dot(v1,v2)

32

In [ ]:
np.cross(v1,v2)

array([-3,  6, -3])

# Determinant
**Q3: Determinant of a Matrix**

Given the matrix:

A = A = [[1, 2, 5], [1,3, 4], [4 ,5, 6]]

Calculate the determinant of the matrix A. Ensure you check if the determinant is non-zero, as this will affect the next operation (inverse).

In [ ]:
A = np.array([[1, 2, 5], [1,3, 4], [4 ,5, 6]])

In [ ]:
A

array([[1, 2, 5],
       [1, 3, 4],
       [4, 5, 6]])

In [ ]:
np.linalg.det(A)

-17.0

# Transpose

**Q4: Transpose of a Matrix**

Given the matrix:

A = [[1, 2, 5], [1,3, 4], [4 ,5, 6]]

Compute the transpose of matrix A. (The transpose of a matrix swaps its rows and columns.)


In [ ]:
m=np.array([[1, 2, 5], [1,3, 4], [4 ,5, 6]])
m


array([[1, 2, 5],
       [1, 3, 4],
       [4, 5, 6]])

In [ ]:
#1st method
np.transpose(m)

array([[1, 1, 4],
       [2, 3, 5],
       [5, 4, 6]])

In [ ]:
# 2nd method
m.T

array([[1, 1, 4],
       [2, 3, 5],
       [5, 4, 6]])

# Inverse
**Q5: Inverse of a Matrix**

Given the matrix in question  3:

A = [[1, 2, 5], [1,3, 4], [4 ,5, 6]]

Compute the inverse of matrix A (if it exists). You should:

First calculate the determinant of the matrix.

If the determinant is non-zero, calculate the inverse of the matrix.


In [ ]:
A   #from Question 3

array([[1, 2, 5],
       [1, 3, 4],
       [4, 5, 6]])

In [ ]:
np.linalg.inv(A)

array([[ 0.11764706, -0.76470588,  0.41176471],
       [-0.58823529,  0.82352941, -0.05882353],
       [ 0.41176471, -0.17647059, -0.05882353]])

# Rank of a Matrix

Q6: Compute the Rank of a Matrix

Given the matrix:

A = [[1, 2], [2, 4], [3, 6]]


In [ ]:
M=np.array([[1, 2], [2, 4], [3, 6]])
M

array([[1, 2],
       [2, 4],
       [3, 6]])

In [ ]:
np.linalg.matrix_rank(M)

1

# . Eigenvalues and Eigenvectors
**Q7: Eigenvalues and Eigenvectors**

Given the matrix:

A = [[4, -2], [1, 1]]

Compute the eigenvalues and eigenvectors of matrix A. Verify the result by multiplying the matrix A by each eigenvector and checking if it corresponds to the eigenvalue times the eigenvector.

In [ ]:
A = np.array([[4, -2], [1, 1]])

In [ ]:
A

array([[ 4, -2],
       [ 1,  1]])

In [ ]:
Eig_val, Eig_vec=np.linalg.eig(A)

In [ ]:
Eig_val

array([3., 2.])

In [ ]:
Eig_vec

array([[0.89442719, 0.70710678],
       [0.4472136 , 0.70710678]])

# Solve a System of Linear Equations
**Solve the system of linear equations**

3x+2y=16

2x−y=4

 solve for x and y.

In [ ]:
# 3x+2y=16

# 2x+y=4


A=np.array([[3,2],[2,1]])

In [ ]:
A

array([[3, 2],
       [2, 1]])

In [ ]:
B=np.array([16,4])

In [ ]:
B

array([16,  4])

In [ ]:
np.linalg.solve(A,B)

array([-8., 20.])