<a href="https://colab.research.google.com/github/madanjha/PythonDS/blob/main/Handson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=50
b=10
c=20
d=30
e=40
a+=b
c-=b
d*=b
e/=b
print(a)
print(c)
print(d)
print(e)


60
10
300
4.0


In [ ]:
a=10
b=20
print(a>b)
print(a>=b)
print(a<b)
print(a<=b)
print(a!=b)

False
False
True
True
True


In [ ]:
a=11
b=4
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)
print(a//b)


In [ ]:
# import modules used here -- sys is a very standard one
import sys

# Gather our code in a main() function
def main():
    print('Hello there', sys.argv[1])
    # Command line args are in sys.argv[1], sys.argv[2] ...
    # sys.argv[0] is the script name itself and can be ignored

# Standard boilerplate to call the main() function to begin
# the program.
if __name__ == '__main__':
    main()

Hello there -f


In [ ]:
def main():
    print(repeat('Yay', False))      ## YayYayYay
    print(repeat('Woo Hoo', True))   ## Woo HooWoo HooWoo Hoo!!!

In [ ]:
marks = int(input('Enter your marks: '))

if marks >= 0 and marks <= 100:
  if marks >= 35 and marks <= 100:
    print('Hurray You passed.')
  else:
    print('Sorry You failed.')
else:
  print('Invalid Input. Please enter a number between 0 and 100.')

Enter your marks: 57
Hurray You passed.


In [ ]:
span=1
test='# is is not the comments it is inside the singl quots'
print(test)

# is is not the comments it is inside the singl quots


In [ ]:
4*3.75-1

14.0

In [ ]:
'doesn\'t'
'"Yes", They said !'

'"Yes", They said !'

In [ ]:
3*'un'+'ne'

'unununne'

In [ ]:
word='python'
word[0]
word[5]
word[-1]
word[-6]
word[0:2]
word[2:5]


'tho'

In [ ]:
#word[:2] + word[2:]

word[:4] + word[4:]

'python'

In [ ]:
squares = [1, 4, 9, 16, 25]
squares

[1, 4, 9, 16, 25]

In [ ]:
squares[3:]

[16, 25]

In [ ]:
squares + [36, 49, 64, 81, 100]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
cubes = [1, 8, 27, 65, 125]
cubes[3] = 64
cubes

[1, 8, 27, 64, 125]

In [ ]:
  rgb = ["Red", "Green", "Blue"]
rgaa=rgb
rgb==rgaa
rgaa[0]="Red"
rgb.append('Yellow')
rgb

['Red', 'Green', 'Blue', 'Yellow']

In [ ]:
letters = ['a', 'b', 'c', 'd']
letters

['a', 'b', 'c', 'd']

In [ ]:
a = ['a', 'b', 'c']
n = [1, 2, 3]
x = [a, n]
x

[['a', 'b', 'c'], [1, 2, 3]]

In [ ]:
x[0][1]

'b'

#**Fabonicc Series**

In [ ]:
a, b = 0, 1
while a < 10:
    print(a)
    a, b = b, a+b

0
1
1
2
3
5
8


In [ ]:
a, b = 0, 1
while a < 10000:
    print(a, end=',')
    a, b = b, a+b

0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,1597,2584,4181,6765,

In [ ]:
def initlog(*args):
    pass   # Remember to implement this!


In [ ]:

def http_error(status):
    match status:
        case 400:
            return "Bad request"
        case 404:
            return "Not found"
        case 418:
            return "I'm a teapot"
        case _:
            return "Something's wrong with the internet"

**Create a student student management system.**

In [ ]:
class Student:
    def __init__(self, name, marks_subject1, marks_subject2):
        self.name = name
        self.marks_subject1 = marks_subject1
        self.marks_subject2 = marks_subject2

    def calculate_average(self):
        return (self.marks_subject1 + self.marks_subject2) / 2

    def display_info(self):
        average = self.calculate_average()
        print(f"Student Name: {self.name}")
        print(f"Marks in Subject 1: {self.marks_subject1}")
        print(f"Marks in Subject 2: {self.marks_subject2}")
        print(f"Average Score: {average:.2f}\n")

In [ ]:
class GraduateStudent(Student):
    def __init__(self, name, marks_subject1, marks_subject2, thesis_title):
        super().__init__(name, marks_subject1, marks_subject2)
        self.thesis_title = thesis_title

    def display_info(self):
        super().display_info()  # Call the method from the base class
        print(f"Thesis Title: {self.thesis_title}\n")

In [ ]:
def main():
    # Creating instances of Student
    student1 = Student("Alice", 85, 90)
    student2 = Student("Bob", 78, 82)

    # Displaying information for undergraduate students
    student1.display_info()
    student2.display_info()

    # Creating an instance of GraduateStudent
    grad_student = GraduateStudent("Charlie", 92, 88, "AI in Healthcare")

    # Displaying information for graduate student
    grad_student.display_info()

if __name__ == "__main__":
    main()

Student Name: Alice
Marks in Subject 1: 85
Marks in Subject 2: 90
Average Score: 87.50

Student Name: Bob
Marks in Subject 1: 78
Marks in Subject 2: 82
Average Score: 80.00

Student Name: Charlie
Marks in Subject 1: 92
Marks in Subject 2: 88
Average Score: 90.00

Thesis Title: AI in Healthcare



#Q2. You have to develope a Bank Account Management System using encapsulation in python.
# The system should allow users to manage their bank accounts by performing common operations like deposit,withdrawal,
# setting account holder name and account number and checking their balance

In [ ]:
class Account:
  def __init__(self, name, accountNo,balance=0):
    self._name = name
    self._accountNo = accountNo
    self._balance = balance

  def deposit(self, amount):
    if amount > 0:
      self._balance += amount
      print(f'Deposit Successful {amount}')
    else:
      print('Invalid amount')

  def withdraw(self, amount):
    if amount > 0 and amount <= self._balance:
      self._balance -= amount
      print(f'Withdrawal Successful {amount}')
    else:
      print('Invalid amount')

  def getBalance(self):
    return self._balance
acc=Account('ram',12345,2000)
acc.deposit(1000)
acc.withdraw(200)
print(acc.getBalance())


Deposit Successful 1000
Withdrawal Successful 200
2800


Q#3. Libary management system, so we need to create a class Book with specific attributes and methods
* that handles the books lending on returning operation.
* The system should check if the copies are avaliable before lending the books and update the availibility after each transaction.


In [ ]:
class Booklib:
  def __init__(self,name,author,copies):
    self.name=name
    self.author=author
    self.copies=copies
  def lend(self):
    if self.copies>0:
      self.copies-=1
      print('book lend  successfully')
    else:
      print('book not available')
  def returnbook(self):
    self.copies+=1
    print('book returned successfully')
book=Booklib('Math','TMH',10)
book.lend()
book.returnbook()


book lend  successfully
book returned successfully


Q#4. write program to perform polymorihim in python.

In [ ]:
class Addition:
  def add(self,a,b):
    return a+b
addnum=Addition()
print(addnum.add(1,2))
print(addnum.add('a','b'))
addString=Addition()
print(addString.add('FistName','Lastname'))



3
ab
FistNameLastname


#Q5 Writ the code for inheritance program

In [ ]:
class Animal:
    def speak(self):
        pass

class Dog(Animal):
    def speak(self):
        return "Woof!"

class Cat(Animal):
    def speak(self):
        return "Meow!"

# Create instances of the derived classes
dog = Dog()
cat = Cat()

# Call the speak method on the instances
print(dog.speak())  # Output: Woof!
print(cat.speak())  # Output: Meow

Woof!
Meow!


#**numpy (Numerical Pyhon)**

Q1. Create a numpy array module and with a data type integer and float

In [ ]:

import numpy as np
int_array = np.array([1, 2, 3, 4, 5,7.11], dtype=int)
print("Integer Array:", int_array)
print("Data Type of Integer Array:", int_array.dtype)

# Create an array of floats
float_array = np.array([1.0, 2.5, 3.8, 4.2,8], dtype=float)
print("Float Array:", float_array)
print("Data Type of Float Array:", float_array.dtype)

Integer Array: [1 2 3 4 5 7]
Data Type of Integer Array: int64
Float Array: [1.  2.5 3.8 4.2 8. ]
Data Type of Float Array: float64


Q2. Create numpy arrays that have zero,one,two,three and four dimensions respectively. Also, print the shape and dimensions of each array.



In [53]:
import numpy as np

zero_darr=np.array(10)
two_darr=np.array([[10,20],[4,5]])
three_darr=np.arange(10,19).reshape(3,3)
four_darr=np.arange(10,26).reshape(4,4)
print("zero_darr:",zero_darr)
print("two_darr:",two_darr)
print("three_darr:",three_darr)
print("four_darr:",four_darr)


zero_darr: 10
two_darr: [[10 20]
 [ 4  5]]
three_darr: [[10 11 12]
 [13 14 15]
 [16 17 18]]
four_darr: [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


In [54]:
zero_darr.shape


()

In [55]:
two_darr.shape


(2, 2)

In [56]:
three_darr.shape


(3, 3)

In [57]:
four_darr.shape

(4, 4)

Q3. change the dimession of a3D array to 2D array

In [70]:
three_darr=np.arange(10,22).reshape(2,3,2)
print(three_darr)
print(three_darr.ndim)
twd=three_darr.reshape(2,6)
print(twd)
print(twd.ndim)

[[[10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]]]
3
[[10 11 12 13 14 15]
 [16 17 18 19 20 21]]
2


In [71]:
three_darr.reshape(2,6)

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21]])

Q4. Create a 2x2, 3x3 and 4x4 identity matrix using numpy methods

In [77]:
arry2by2=np.identity(2,dtype=int)
print("arry2by2",arry2by2)
arry3by3=np.identity(3,dtype=float)
print("arry3by3",arry3by3)
arry4by4=np.identity(4)
print("arry4by4",arry4by4)

arry2by2 [[1 0]
 [0 1]]
arry3by3 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
arry4by4 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Q5. Create a numpy array and negate it using a 0D array

In [93]:
import numpy as np

array_1d = np.array([1, 2, -3, 4, -5])
print("Original Array:", array_1d)

zero_d_array = np.array(-1)

negated_array = np.negative( array_1d*-zero_d_array)
print("Negated Array:", negated_array)

Original Array: [ 1  2 -3  4 -5]
Negated Array: [-1 -2  3 -4  5]


Q6. Create a numpy array with shape 2x5 that has all the element a zeros.

In [99]:
array2x5=np.zeros([2,5])
print("array2x5",array2x5)

array2x5 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Q7. create numpy array that has a shape of 3x5 and all the element in arrays are 5

In [102]:
array3x5=np.full((3,5),5)
print("array3x5\n",array3x5)

array3x5
 [[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


Q8. Create an arrays with random integer in range  0-100 and sample size should be 25.

In [113]:
randomNo=np.random.randint(0,101,25)
print("randomNo\n",randomNo)

randomNo
 [16 70 71 57 33 29 40 58 63 83  9 48 73 54 84 81  5 33 34 45 20 44 51 94
 50]


Q9. Create an array of random integer in range 1 to 50 take the sample size of 12 an calculate their mean.

In [135]:
randomMean=np.random.randint(1,51,12).mean()
print("randomMean\n",randomMean)

randomMean
 22.5


Q10.Creat an with random integer from 1 to 50 with sample size 10, sort the array and display the indeces of the sorted array.

In [140]:
sortArray=np.random.randint(1,51,10)
print("sortArray\n",sortArray)
argasrt=sortArray.argsort()
print("sortArray\n",argasrt)

sortArray
 [28 38 15 23 40 23 18 33 15 29]
sortArray
 [2 8 6 3 5 0 9 7 1 4]


Q11. Create a 2D array /matrix and calculate the transpose of that matrix.

In [146]:
TDmatrix=np.identity(2,dtype=int)
print("TDmatrix\n",TDmatrix)
transpose=TDmatrix.T
print("transpose\n",transpose)

TDmatrix
 [[1 0]
 [0 1]]
transpose
 [[1 0]
 [0 1]]


Q11. Create nympy array with shape 3x3 thathas all elements as 1 (show 3 different method.)

In [153]:
np.ones((3,3))



array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [149]:
np.full((3,3),1)


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [162]:
np.zeros((3,3))+1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Q13.Create an array filed with random integer fro 1 to 100 with sample size 30 calculate sum,min max,variance, stddevation.

In [170]:
arry1=np.random.randint(1,101,30)
print("arry1\n",arry1)
print("sum\n",arry1.sum())
print("min\n",arry1.min())
print("max\n",arry1.max())
print("variance\n",arry1.var())
print("stddevation\n",arry1.std())
print("mean\n",arry1.mean())

arry1
 [18 54 18 94 79 73 26 97 74 81 28 70 91  6 24 52 90 84 34 48 90 91 42 53
 44 90 36 92  8 84]
sum
 1771
min
 6
max
 97
variance
 843.6988888888889
stddevation
 29.04649529442216
mean
 59.03333333333333


Q14. Create and array with range 1-1000 and sample size 50 and step size is 2.
a.Print the first 10 element of array

In [188]:
array2=np.arange(1,1001,2)
print("array2",array2)
array2slice=np.random.choice(array2,50)
print("array2slice",array2slice)
array2slice1=array2slice[:10]
print("array2slice1",array2slice1)

array2 [  1   3   5 ... 995 997 999]
array2slice [961 379 975 ... 483 283 805]
array2slice1 [961 379 975 163 611 347 489 959 737  29]


In [189]:
array2[:10]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [194]:
array2slice=np.random.choice(array2,50)
print("array2slice",array2slice)
array2slice[10:26]

array2slice [885 349 829 ... 979 223 789]


array([903, 503, 861, ...,  59, 473, 503])

C.print the last ten element of using negative indexing

In [196]:
array2slice=np.random.choice(array2,50)
print("array2slice",array2slice)
array2slice[-10]

array2slice [485 507 769 ... 181 185 453]


223

Q15. Create an array of 1-10 and perform the following operation
    * a. insert the element at the end of array
    *  b. insert the element befor 5
    * c. update te element 6 s 60
    * d. delete the element 60 in the update array.
    * e. create a function to search for element








