<a href="https://colab.research.google.com/github/madanjha/PythonDS/blob/main/LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Liner Algebra Hands-on session:**

In [10]:
import numpy as np
import scipy.linalg as la
import matplotlib.pyplot as plt

**1. Matrix Operations**

Q1: Basic Matrix Operations

Create two matrices:

A (3x2) = [[1, 2], [3, 4], [5, 6]]

B (2x3) = [[7, 8, 9], [10, 11, 12]]

Perform the following operations:

Matrix Addition: Compute A + B (if possible).

Matrix Multiplication: Compute the product of matrices A * B (if possible).

Scalar Multiplication: Multiply matrix A by a scalar k = 5.


In [13]:
A=np.random.randint(1,5,size=(3,2))
B=np.random.randint(1,5,size=(2,3))
print(A)
print(B)




[[2 4]
 [3 2]
 [1 4]]
[[3 1 1]
 [3 3 2]]


In [14]:
np.add(A,B)

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [15]:
np.dot(A,B)

array([[18, 14, 10],
       [15,  9,  7],
       [15, 13,  9]])

In [16]:
np.cross(A,B)

ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (3,) and arg 1 with shape (2,).

**2. Dot and Cross Product**
**Q2: Dot and Cross Product**
Create two 3D vectors:
v1 = [1, 2, 3]
v2 = [4, 5, 6]
Compute the following:
Dot Product: Calculate the dot product of v1 and v2.
Cross Product: Calculate the cross product of v1 and v2.


In [17]:
v1=np.array([1,2,3])
v2=np.array([4,5,6])
print(v1)
print(v2)


[1 2 3]
[4 5 6]


In [18]:
np.cross(v1,v2)

array([-3,  6, -3])

In [19]:
np.dot(v1,v2)

32

## **3. Determinant**
Q3: Determinant of a Matrix **bold text**

Given the matrix:
A = [[4, 7], [2, 6]]

Calculate the determinant of the matrix A. Ensure you check if the determinant is non-zero, as this will affect the next operation (inverse)

In [20]:
A=np.array([[4,7],[2,6]])
print(A)

[[4 7]
 [2 6]]


In [21]:
np.linalg.det(A)


10.000000000000002

In [23]:
Ainv=np.linalg.inv(A)
print(Ainv)

[[ 0.6 -0.7]
 [-0.2  0.4]]


**4. Transpose**
**Q4: Transpose of a Matrix**

Given the matrix:

A = [[1, 2, 5], [1,3, 4], [4 ,5, 6]]

Compute the transpose of matrix A. (The transpose of a matrix swaps its rows and columns.)


In [24]:
A=np.array([[1,2,5],[1,3,4],[4,5,6]])
print(A)

[[1 2 5]
 [1 3 4]
 [4 5 6]]


In [26]:
A_det=np.linalg.det(A)
print(A_det)

-17.0


In [25]:
Atranpose=np.transpose(A)
print(Atranpose)

[[1 1 4]
 [2 3 5]
 [5 4 6]]


**5. Inverse**
**Q5: Inverse of a Matrix**

Given the matrix in question  3:

A = [[1, 2, 5], [1,3, 4], [4 ,5, 6]]
Compute the inverse of matrix A (if it exists).
You should:
First calculate the determinant of the matrix.
If the determinant is non-zero, calculate the inverse of the matrix


In [27]:
A_matx=np.array([[1,2,5],[1,3,4],[4,5,6]])
print(A_matx)

[[1 2 5]
 [1 3 4]
 [4 5 6]]


In [28]:
Adet=np.linalg.det(A_matx)
print(Adet)

-17.0


In [32]:
a_inv=np.linalg.inv(A_matx)
print(a_inv)

[[ 0.11764706 -0.76470588  0.41176471]
 [-0.58823529  0.82352941 -0.05882353]
 [ 0.41176471 -0.17647059 -0.05882353]]


**Rank of a Matrix**

**Q6: Compute the Rank of a Matrix**

Given the matrix:

A = [[1, 2], [2, 4], [3, 6]]


In [33]:
Mtx_A=np.array([[1,2],[2,4],[3,6]])
print(Mtx_A)
rank=np.linalg.matrix_rank(Mtx_A)
print(rank)


[[1 2]
 [2 4]
 [3 6]]
1



**Q7: Eigenvalues and Eigenvectors**

Given the matrix:

A = [[4, -2], [1, 1]]

Compute the eigenvalues and eigenvectors of matrix A. Verify the result by multiplying the matrix A by each eigenvector and checking if it corresponds to the eigenvalue times the eigenvector

In [34]:
A_mtx=np.array([[4,-2],[1,1]])
print(A_mtx)

[[ 4 -2]
 [ 1  1]]


In [35]:
EigVal=np.linalg.eigvals(A_mtx)
print(EigVal)

[3. 2.]


In [36]:
EigVect=np.linalg.eig(A_mtx)
print(EigVect)

EigResult(eigenvalues=array([3., 2.]), eigenvectors=array([[0.89442719, 0.70710678],
       [0.4472136 , 0.70710678]]))


**8. Solving Linear Systems Using Matrix Operations**

**Q8: Solve a System of Linear Equations**

Solve the system of linear equations:

3x+2y=16

2x−y=4

You should use the coefficient matrix and the constant matrix to solve for x and

In [39]:
Xval=np.array([[3,2],[2,-1]])
Bval=np.array([16,4])
print(Xval)
print(Bval)

[[ 3  2]
 [ 2 -1]]
[16  4]


In [40]:
sol=np.linalg.solve(Xval,Bval)
print(sol)

[3.42857143 2.85714286]
