<a href="https://colab.research.google.com/github/madanjha/PythonDS/blob/main/NumpyHandson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY HANDSON

In [ ]:
import numpy as np

Q1. Create a numpy array module and with a data type integer and float

In [ ]:
Arr1 = np.array([1,2,3,4.1,5,6],dtype = int)
Arr1

array([1, 2, 3, 4, 5, 6])

In [ ]:
Arr2 = np.array([1,2,3,4.1,5,6],dtype = float)
Arr2

array([1. , 2. , 3. , 4.1, 5. , 6. ])

In [ ]:
Arr1.dtype

dtype('int32')

In [ ]:
Arr2.dtype

dtype('float64')

Q2. Create numpy arrays that have zero,one,two,three and four dimensions respectively. Also, print the shape and dimensions of each array.

In [ ]:
ZD = np.array(45)
ZD

array(45)

In [ ]:
ZD.shape

()

In [ ]:
ZD.ndim

0

In [ ]:
OD = np.array([1,2,3,4,5])
OD

array([1, 2, 3, 4, 5])

In [ ]:
OD.shape #5 columns only

(5,)

In [ ]:
OD.ndim

1

In [ ]:
TD = np.array([[1,2,3],[4,5,6]]) #matrix
TD

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
TD.shape

(2, 3)

In [ ]:
TD.ndim

2

In [ ]:
ThD = np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])  #images and video data only
ThD

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [ ]:
ThD.shape

(2, 2, 3)

In [ ]:
ThD.ndim

3

In [ ]:
FD = np.array([[[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]],[[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]]])  #computer vision
FD

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[10, 20, 30],
         [40, 50, 60]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[10, 20, 30],
         [40, 50, 60]]]])

In [ ]:
FD.shape

(2, 2, 2, 3)

In [ ]:
FD.ndim

4

Q3. Change the dimension of a 3D array to a 2D array

In [ ]:
ThD = np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])  #images and video data only
ThD

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [ ]:
Arr2D = ThD.reshape(3,4)
Arr2D

array([[ 1,  2,  3,  4],
       [ 5,  6, 10, 20],
       [30, 40, 50, 60]])

In [ ]:
Arr2D.ndim

2

Q4. Create a 2x2, 3x3 and 4x4 identity matrix using numpy methods

In [ ]:
#2x2
np.identity(2,dtype = int) #always creates a square matix

array([[1, 0],
       [0, 1]])

In [ ]:
#3x3
np.eye(3,dtype=int) #we can change the shape in eye()

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
#3x4
np.eye(3,4) #rows ,columns

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
#4x4
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

Q5. Create a numpy array and negate it using a 0D array

In [ ]:
Arr = np.arange(1,10)
Arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
Zd = np.array(-1)
Zd

array(-1)

In [ ]:
Result = Arr * Zd
Result

array([-1, -2, -3, -4, -5, -6, -7, -8, -9])

Q6. Create a numpy array with shape 2x5 that has all the elements as zeros

In [ ]:
np.zeros([2,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Q7. Create a numpy array that has a shape of 3x5 and all the elements in the array are 5

In [ ]:
np.full((3,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

Q8. Create an array with random integers in the range 0-100 and the sample size should be 25

In [ ]:
np.random.randint(0,100,25)

array([96, 47, 81, 91, 33, 20,  6, 40, 36, 81, 50, 83,  5, 98, 58, 25, 77,
        0, 51, 54, 85, 42, 22, 92, 62])

Q9. Create an array of random integers in the range 1-50, take the sample size of 12 and calculate their mean.

In [ ]:
Arr_random = np.random.randint(1,51,12)
Arr_random

array([12, 28, 45, 34, 24, 41,  1, 46, 34, 36, 42, 30])

In [ ]:
np.mean(Arr_random)

31.083333333333332

Q10. Create an array with random integers from 1 to 50, with sample size 10. Sort the array and display the indices of the sorted array.

In [ ]:
arr = np.random.randint(1,51,10)
arr

array([42, 35, 11, 21, 33, 48, 10, 25, 28, 23])

In [ ]:
np.argsort(arr)

array([6, 2, 3, 9, 7, 8, 4, 1, 0, 5], dtype=int64)

In [ ]:
sorted = np.sort(arr)

In [ ]:
sorted

array([10, 11, 21, 23, 25, 28, 33, 35, 42, 48])

In [ ]:
np.argsort(sorted)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

Q11. Create a 2D array / matrix and calculate the transpose of that matrix

In [ ]:
TD

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.transpose(TD)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
TD.T

array([[1, 4],
       [2, 5],
       [3, 6]])

Q12. Create a numpy array with shape 3x3 that has all elements as 1 (show 3 different methods)

In [ ]:
np.ones((3,3),dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.full((3,3),1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.zeros((3,3),dtype = int) + 1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

Q13. Create an array filled with random integers from 1-100, with sample size 30. And calculate sum,min,max,var,std.

In [ ]:
A = np.random.randint(1,101,30)
A

array([75, 41, 31, 23, 35, 59, 84, 41, 56, 22, 78,  1,  8, 32, 89, 95, 39,
       80, 55, 92, 15, 83, 60, 82, 87, 75, 78, 63, 86, 59])

In [ ]:
np.sum(A)

1724

In [ ]:
np.min(A)

1

np.max(A)

In [ ]:
np.var(A)

729.2488888888887

In [ ]:
np.std(A)

27.00460866016926

In [ ]:
np.mean(A)

57.46666666666667

Q14. Create an array with range of 1- 1000 ad sample size 50 ans step size 2

a. Print the first 10 elements of the array.

In [ ]:
Array = np.arange(1,1001,2)
Array

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
       105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
       131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
       157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
       183, 185, 187, 189, 191, 193, 195, 197, 199, 201, 203, 205, 207,
       209, 211, 213, 215, 217, 219, 221, 223, 225, 227, 229, 231, 233,
       235, 237, 239, 241, 243, 245, 247, 249, 251, 253, 255, 257, 259,
       261, 263, 265, 267, 269, 271, 273, 275, 277, 279, 281, 283, 285,
       287, 289, 291, 293, 295, 297, 299, 301, 303, 305, 307, 309, 311,
       313, 315, 317, 319, 321, 323, 325, 327, 329, 331, 333, 335, 337,
       339, 341, 343, 345, 347, 349, 351, 353, 355, 357, 359, 36

In [ ]:
Array = Array[:50]
Array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
Array[:10]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
Ar = np.random.choice(Array,50,replace = False)

In [ ]:
Ar

array([547,   3, 993, 929, 641, 375, 797, 503, 585,  41,  27, 957, 423,
       871, 465, 239,  23, 917, 517, 213, 541, 613, 861, 853, 359, 577,
       741,  59, 597, 421, 151, 343, 977, 139, 469, 755,  87, 513,  71,
       231, 145, 441, 319, 721, 255, 439, 533, 963, 203, 561])

In [ ]:
Ar.size

50

In [ ]:
Ar[:10]

array([547,   3, 993, 929, 641, 375, 797, 503, 585,  41])

b. Print the elements from index 10 to 25

In [ ]:
Ar[10:26]

array([ 27, 957, 423, 871, 465, 239,  23, 917, 517, 213, 541, 613, 861,
       853, 359, 577])

c. Print the last ten elements using negative indexing

In [ ]:
Ar[-10:]

array([145, 441, 319, 721, 255, 439, 533, 963, 203, 561])

Q15. Create an array of range 1-10 and perform the following operations:
a. insert an element at the end of the array
b.insert an element for 5
c.update the element 6 as 60
d.delete the element 60 in the updated array
e.create a function to search for a element